#!/bin/bash

# Set the URL for the WFS service
URL="https://geoserver.plandata.dk/geoserver/wfs"
SERVICE_PARAMS="servicename=wfs&request=getcapabilities&service=wfs&typename=pdk:theme_pdk_lokalplan_forslag_v"

# Specify the layer you want to update
SERVER_LAYER="pdk:theme_pdk_lokalplan_forslag_v"
LOCAL_LAYER="theme_pdk_lokalplan_forslag_v"

# Generate the timestamp for the day before yesterday at 17:00
# Read the last download timestamp from last_download.txt
LAST_DOWNLOAD_TIMESTAMP=$(cat last_download.txt)
echo "Using timestamp from last_download.txt: $LAST_DOWNLOAD_TIMESTAMP"

# Temporary table name for loading new data
TEMP_TABLE="plandata.tmp"

# Check if the temporary table exists and drop it before creating a new one
echo "Dropping temporary table if it exists..."
psql -d crawler -c "DROP TABLE IF EXISTS $TEMP_TABLE;"

# Fetch the entire layer without filtering by timestamp
echo "Fetching all records for layer: $SERVER_LAYER and loading into temporary table: $TEMP_TABLE"

ogr2ogr -f "PostgreSQL" PG:"dbname=crawler" \
    --config OGR_WFS_URL "$URL" \
    --config OGR_WFS_BASEURL "$URL" \
    -where datoopdt > $LAST_DOWNLOAD_TIMESTAMP\
    -nln "$TEMP_TABLE" \
    -lco SCHEMA=plandata \
    -skipFailures \
    "$URL?$SERVICE_PARAMS" \
    "$SERVER_LAYER"

# Check if the ogr2ogr command was successful (but do not stop the script if it fails)
if [ $? -eq 0 ]; then
    echo "Successfully appended all records to the temporary table from $SERVER_LAYER"
else
    echo "Warning: Failed to append records to the temporary table from $SERVER_LAYER" >> error_log.txt  # Log the error
fi

# Reintroduce the SQL-based update to filter by timestamp
echo "Updating existing records in $LOCAL_LAYER"
psql -d crawler -c "UPDATE plandata.$LOCAL_LAYER 
    SET 
        ogc_fid = source.ogc_fid,
        gml_id = source.gml_id,
        oid_ = source.oid_,
        id = source.id,
        planid = source.planid,
        komnr = source.komnr,
        objektkode = source.objektkode,
        plantype = source.plantype,
        plannr = source.plannr,
        plannavn = source.plannavn,
        anvgen = source.anvgen,
        datoforsl = source.datoforsl,
        datovedt = source.datovedt,
        datoaflyst = source.datoaflyst,
        datoikraft = source.datoikraft,
        datostart = source.datostart,
        datoslut = source.datoslut,
        datoattr = source.datoattr,
        datogeom = source.datogeom,
        doklink = source.doklink,
        distrikt = source.distrikt,
        zone = source.zone,
        bebygpct = source.bebygpct,
        bebygpctaf = source.bebygpctaf,
        bebygpctar = source.bebygpctar,
        m3_m2 = source.m3_m2,
        maxetager = source.maxetager,
        maxbygnhjd = source.maxbygnhjd,
        minmiljo = source.minmiljo,
        maxmiljo = source.maxmiljo,
        bevarbest = source.bevarbest,
        bebyggrad = source.bebyggrad,
        mingrund = source.mingrund,
        dataprod = source.dataprod,
        digigrundl = source.digigrundl,
        digigrundd = source.digigrundd,
        datooprt = source.datooprt,
        datoopdt = source.datoopdt,
        anvendelsegenerel = source.anvendelsegenerel,
        kommunenavn = source.kommunenavn,
        zonestatus = source.zonestatus,
        planstatus = source.planstatus,
        megawatt = source.megawatt,
        vvmredeg = source.vvmredeg,
        sforhold = source.sforhold,
        minuds = source.minuds,
        eareal = source.eareal,
        earealh = source.earealh,
        m3_m2h = source.m3_m2h,
        ianvreg = source.ianvreg,
        izonereg = source.izonereg,
        iomfangreg = source.iomfangreg,
        iudstykreg = source.iudstykreg,
        kompleks = source.kompleks,
        kbeskriv = source.kbeskriv,
        vindbeskriv = source.vindbeskriv,
        udstykforbud = source.udstykforbud,
        statsplan = source.statsplan,
        sforaktuel = source.sforaktuel,
        anvspec1 = source.anvspec1,
        bygpct1 = source.bygpct1,
        bygpcth1 = source.bygpcth1,
        eareal1 = source.eareal1,
        earealh1 = source.earealh1,
        m3_m21 = source.m3_m21,
        m3_m2h1 = source.m3_m2h1,
        maxbhjd1 = source.maxbhjd1,
        maxetage1 = source.maxetage1,
        bygpctar1 = source.bygpctar1,
        minuds1 = source.minuds1,
        udstykfb1 = source.udstykfb1,
        plankap1 = source.plankap1,
        plankapia1 = source.plankapia1,
        forvprod1 = source.forvprod1,
        forvprodia1 = source.forvprodia1,
        anvspec2 = source.anvspec2,
        bygpct2 = source.bygpct2,
        bygpcth2 = source.bygpcth2,
        eareal2 = source.eareal2,
        earealh2 = source.earealh2,
        m3_m22 = source.m3_m22,
        m3_m2h2 = source.m3_m2h2,
        maxbhjd2 = source.maxbhjd2,
        maxetage2 = source.maxetage2,
        bygpctar2 = source.bygpctar2,
        minuds2 = source.minuds2,
        udstykfb2 = source.udstykfb2,
        plankap2 = source.plankap2,
        plankapia2 = source.plankapia2,
        forvprod2 = source.forvprod2,
        forvprodia2 = source.forvprodia2,
        anvspec3 = source.anvspec3,
        bygpct3 = source.bygpct3,
        bygpcth3 = source.bygpcth3,
        eareal3 = source.eareal3,
        earealh3 = source.earealh3,
        m3_m23 = source.m3_m23,
        m3_m2h3 = source.m3_m2h3,
        maxbhjd3 = source.maxbhjd3,
        maxetage3 = source.maxetage3,
        bygpctar3 = source.bygpctar3,
        minuds3 = source.minuds3,
        udstykfb3 = source.udstykfb3,
        plankap3 = source.plankap3,
        plankapia3 = source.plankapia3,
        forvprod3 = source.forvprod3,
        forvprodia3 = source.forvprodia3,
        anvspec4 = source.anvspec4,
        bygpct4 = source.bygpct4,
        bygpcth4 = source.bygpcth4,
        eareal4 = source.eareal4,
        earealh4 = source.earealh4,
        m3_m24 = source.m3_m24,
        m3_m2h4 = source.m3_m2h4,
        maxbhjd4 = source.maxbhjd4,
        maxetage4 = source.maxetage4,
        bygpctar4 = source.bygpctar4,
        minuds4 = source.minuds4,
        udstykfb4 = source.udstykfb4,
        plankap4 = source.plankap4,
        plankapia4 = source.plankapia4,
        forvprod4 = source.forvprod4,
        forvprodia4 = source.forvprodia4,
        anvspec5 = source.anvspec5,
        bygpct5 = source.bygpct5,
        bygpcth5 = source.bygpcth5,
        eareal5 = source.eareal5,
        earealh5 = source.earealh5,
        m3_m25 = source.m3_m25,
        m3_m2h5 = source.m3_m2h5,
        maxbhjd5 = source.maxbhjd5,
        maxetage5 = source.maxetage5,
        bygpctar5 = source.bygpctar5,
        minuds5 = source.minuds5,
        udstykfb5 = source.udstykfb5,
        plankap5 = source.plankap5,
        plankapia5 = source.plankapia5,
        forvprod5 = source.forvprod5,
        forvprodia5 = source.forvprodia5,
        anvspec6 = source.anvspec6,
        bygpct6 = source.bygpct6,
        bygpcth6 = source.bygpcth6,
        eareal6 = source.eareal6,
        earealh6 = source.earealh6,
        m3_m26 = source.m3_m26,
        m3_m2h6 = source.m3_m2h6,
        maxbhjd6 = source.maxbhjd6,
        maxetage6 = source.maxetage6,
        bygpctar6 = source.bygpctar6,
        minuds6 = source.minuds6,
        udstykfb6 = source.udstykfb6,
        plankap6 = source.plankap6,
        plankapia6 = source.plankapia6,
        forvprod6 = source.forvprod6,
        forvprodia6 = source.forvprodia6,
        anvspec7 = source.anvspec7,
        bygpct7 = source.bygpct7,
        bygpcth7 = source.bygpcth7,
        eareal7 = source.eareal7,
        earealh7 = source.earealh7,
        m3_m27 = source.m3_m27,
        m3_m2h7 = source.m3_m2h7,
        maxbhjd7 = source.maxbhjd7,
        maxetage7 = source.maxetage7,
        bygpctar7 = source.bygpctar7,
        minuds7 = source.minuds7,
        udstykfb7 = source.udstykfb7,
        plankap7 = source.plankap7,
        plankapia7 = source.plankapia7,
        forvprod7 = source.forvprod7,
        forvprodia7 = source.forvprodia7,
        anvspec8 = source.anvspec8,
        bygpct8 = source.bygpct8,
        bygpcth8 = source.bygpcth8,
        eareal8 = source.eareal8,
        earealh8 = source.earealh8,
        m3_m28 = source.m3_m28,
        m3_m2h8 = source.m3_m2h8,
        maxbhjd8 = source.maxbhjd8,
        maxetage8 = source.maxetage8,
        bygpctar8 = source.bygpctar8,
        minuds8 = source.minuds8,
        udstykfb8 = source.udstykfb8,
        plankap8 = source.plankap8,
        plankapia8 = source.plankapia8,
        forvprod8 = source.forvprod8,
        forvprodia8 = source.forvprodia8,
        anvspec9 = source.anvspec9,
        bygpct9 = source.bygpct9,
        bygpcth9 = source.bygpcth9,
        eareal9 = source.eareal9,
        earealh9 = source.earealh9,
        m3_m29 = source.m3_m29,
        m3_m2h9 = source.m3_m2h9,
        maxbhjd9 = source.maxbhjd9,
        maxetage9 = source.maxetage9,
        bygpctar9 = source.bygpctar9,
        minuds9 = source.minuds9,
        udstykfb9 = source.udstykfb9,
        plankap9 = source.plankap9,
        plankapia9 = source.plankapia9,
        forvprod9 = source.forvprod9,
        forvprodia9 = source.forvprodia9,
        anvspec10 = source.anvspec10,
        bygpct10 = source.bygpct10,
        bygpcth10 = source.bygpcth10,
        eareal10 = source.eareal10,
        earealh10 = source.earealh10,
        m3_m210 = source.m3_m210,
        m3_m2h10 = source.m3_m2h10,
        maxbhjd10 = source.maxbhjd10,
        maxetage10 = source.maxetage10,
        bygpctar10 = source.bygpctar10,
        minuds10 = source.minuds10,
        udstykfb10 = source.udstykfb10,
        plankap10 = source.plankap10,
        plankapia10 = source.plankapia10,
        forvprod10 = source.forvprod10,
        forvprodia10 = source.forvprodia10,
        abestem1 = source.abestem1,
        abestem2 = source.abestem2,
        abestem3 = source.abestem3,
        datoudloeb1 = source.datoudloeb1,
        datoudloeb2 = source.datoudloeb2,
        datoudloeb3 = source.datoudloeb3,
        datoudloeb4 = source.datoudloeb4,
        datoudloeb5 = source.datoudloeb5,
        datoudloeb6 = source.datoudloeb6,
        datoudloeb7 = source.datoudloeb7,
        datoudloeb8 = source.datoudloeb8,
        datoudloeb9 = source.datoudloeb9,
        datoudloeb10 = source.datoudloeb10,
        fleksibel1 = source.fleksibel1,
        fleksibel2 = source.fleksibel2,
        fleksibel3 = source.fleksibel3,
        fleksibel4 = source.fleksibel4,
        fleksibel5 = source.fleksibel5,
        fleksibel6 = source.fleksibel6,
        fleksibel7 = source.fleksibel7,
        fleksibel8 = source.fleksibel8,
        fleksibel9 = source.fleksibel9,
        fleksibel10 = source.fleksibel10,
        maxboligenhed1 = source.maxboligenhed1,
        maxboligenhed2 = source.maxboligenhed2,
        maxboligenhed3 = source.maxboligenhed3,
        maxboligenhed4 = source.maxboligenhed4,
        maxboligenhed5 = source.maxboligenhed5,
        maxboligenhed6 = source.maxboligenhed6,
        maxboligenhed7 = source.maxboligenhed7,
        maxboligenhed8 = source.maxboligenhed8,
        maxboligenhed9 = source.maxboligenhed9,
        maxboligenhed10 = source.maxboligenhed10,
        maxboligenhed = source.maxboligenhed,
        udstykantal1 = source.udstykantal1,
        udstykantal2 = source.udstykantal2,
        udstykantal3 = source.udstykantal3,
        udstykantal4 = source.udstykantal4,
        udstykantal5 = source.udstykantal5,
        udstykantal6 = source.udstykantal6,
        udstykantal7 = source.udstykantal7,
        udstykantal8 = source.udstykantal8,
        udstykantal9 = source.udstykantal9,
        udstykantal10 = source.udstykantal10,
        udstykantal = source.udstykantal,
        maxuds1 = source.maxuds1,
        maxuds2 = source.maxuds2,
        maxuds3 = source.maxuds3,
        maxuds4 = source.maxuds4,
        maxuds5 = source.maxuds5,
        maxuds6 = source.maxuds6,
        maxuds7 = source.maxuds7,
        maxuds8 = source.maxuds8,
        maxuds9 = source.maxuds9,
        maxuds10 = source.maxuds10,
        maxuds = source.maxuds,
        udstykningsplan = source.udstykningsplan,
        antal1 = source.antal1,
        antal2 = source.antal2,
        antal3 = source.antal3,
        antal4 = source.antal4,
        antal5 = source.antal5,
        antal6 = source.antal6,
        antal7 = source.antal7,
        antal8 = source.antal8,
        antal9 = source.antal9,
        antal10 = source.antal10,
        geometri = source.geometri
    FROM (SELECT * FROM $TEMP_TABLE WHERE datoopdt > '$LAST_DOWNLOAD_TIMESTAMP') AS source 
    WHERE plandata.$LOCAL_LAYER.ogc_fid = source.ogc_fid;"

# Check if the update command was successful
if [ $? -eq 0 ]; then
    echo "Successfully updated existing records in $LOCAL_LAYER"
else
    echo "Error updating existing records in $LOCAL_LAYER" >> error_log.txt  # Log the error
fi
