#!/bin/bash
URL="https://geoserver.plandata.dk/geoserver/wfs?servicename=wfs&request=getcapabilities&service=wfs"

ogr2ogr -f "PostgreSQL" PG:"dbname=sk user=crawler password=gYKchc21hx5RNUvX schema=plandata" -skipfailures $URL
